/* eslint-disable prettier/prettier */
export enum WorkLocationEnums {
  ON_SITE = 'On Site',
  REMOTE = 'Remote',
  HYBRID = 'Hybrid',
}
export enum EmploymentTypeEnums {
  FULL_TIME = 'Full Time',
  REMOTE = 'Part Time',
  HYBRID = 'Contract',
}
export enum JobPostingStatusEnums {
  DRAFT = 'Draft',
  PENDING = 'Pending',
  POSTED = 'Posted',
  EXPIRED = 'Expired',
}
export enum JobIndustryEnums {
  'AGRICULTURE_FORESTRY_FISHING' = 'AgricultureForestryFishing',
  'ANIMAL_HEALTH_VETERINARY' = 'AnimalHealthVeterinary',
  'ARCHITECTURE_URBAN_PLANNING' = 'ArchitectureUrbanPlanning',
  'ARTS_CULTURE_DESIGN' = 'ArtsCultureDesign',
  'AEROSPACE_AVIATION' = 'AerospaceAviation',
  'AUTOMOTIVE' = 'Automotive',
  'BANKING_FINANCE' = 'BankingFinance',
  'BIOTECHNOLOGY_PHARMACEUTICALS' = 'BiotechnologyPharmaceuticals',
  'BUSINESS_CONSULTING' = 'BusinessConsulting',
  'CHEMICALS' = 'Chemicals',
  'CIVIL_ENGINEERING' = 'CivilEngineering',
  'COMMUNICATIONS_PUBLIC_RELATIONS' = 'CommunicationsPublicRelations',
  'CONSTRUCTION' = 'Construction',
  'CONSUMER_GOODS' = 'ConsumerGoods',
  'DEFENSE_MILITARY' = 'DefenseMilitary',
  'EDUCATION_TRAINING' = 'EducationTraining',
  'ELECTRONICS_SEMICONDUCTORS' = 'ElectronicsSemiconductors',
  'ENERGY_UTILITIES' = 'EnergyUtilities',
  'ENGINEERING' = 'Engineering',
  'ENTERTAINMENT_MEDIA' = 'EntertainmentMedia',
  'ENVIRONMENTAL_SERVICES' = 'EnvironmentalServices',
  'EVENTS_SERVICES' = 'EventsServices',
  'FASHION_APPAREL' = 'FashionApparel',
  'FILM_TV_MUSIC' = 'FilmTVMusic',
  'FOOD_BEVERAGE' = 'FoodBeverage',
  'FURNITURE_HOME_FURNISHINGS' = 'FurnitureHomeFurnishings',
  'GAMING_VIDEO_GAMES' = 'GamingVideoGames',
  'GOVERNMENT_PUBLIC_ADMINISTRATION' = 'GovernmentPublicAdministration',
  'GRAPHIC_DESIGN' = 'GraphicDesign',
  'HEALTHCARE_MEDICAL' = 'HealthcareMedical',
  'HOSPITALITY_TOURISM' = 'HospitalityTourism',
  'HUMAN_RESOURCES' = 'HumanResources',
  'INDUSTRIAL_AUTOMATION' = 'IndustrialAutomation',
  'INFORMATION_TECHNOLOGY' = 'InformationTechnology',
  'INSURANCE' = 'Insurance',
  'INTERNATIONAL_AFFAIRS' = 'InternationalAffairs',
  'INVESTMENT_BANKING' = 'InvestmentBanking',
  'JOURNALISM_WRITING_EDITING' = 'JournalismWritingEditing',
  'LEGAL_LAW' = 'LegalLaw',
  'LOGISTICS_SUPPLY_CHAIN' = 'LogisticsSupplyChain',
  'LUXURY_GOODS_JEWELRY' = 'LuxuryGoodsJewelry',
  'MANUFACTURING' = 'Manufacturing',
  'MARITIME_SHIPPING' = 'MaritimeShipping',
  'MARKETING_ADVERTISING' = 'MarketingAdvertising',
  'MECHANICAL_OR_INDUSTRIAL_ENGINEERING' = 'MechanicalOrIndustrialEngineering',
  'MINING_METALS' = 'MiningMetals',
  'MUSEUMS_HERITAGE' = 'MuseumsHeritage',
  'NANOTECHNOLOGY' = 'Nanotechnology',
  'NON_PROFIT_VOLUNTEERING' = 'NonProfitVolunteering',
  'OIL_GAS' = 'OilGas',
  'PACKAGING_PRINTING' = 'PackagingPrinting',
  'PERFORMING_ARTS' = 'PerformingArts',
  'PHOTOGRAPHY' = 'Photography',
  'PUBLIC_SAFETY_EMERGENCY_SERVICES' = 'PublicSafetyEmergencyServices',
  'PUBLISHING' = 'Publishing',
  'REAL_ESTATE_PROPERTY_MANAGEMENT' = 'RealEstatePropertyManagement',
  'RENEWABLE_ENERGY_ENVIRONMENT' = 'RenewableEnergyEnvironment',
  'RESEARCH_DEVELOPMENT' = 'ResearchDevelopment',
  'RETAIL' = 'Retail',
  'ROBOTICS' = 'Robotics',
  'SALES' = 'Sales',
  'SCIENCE_RESEARCH' = 'ScienceResearch',
  'SECURITY_LAW_ENFORCEMENT' = 'SecurityLawEnforcement',
  'SOCIAL_SERVICES' = 'SocialServices',
  'SPORTS_FITNESS' = 'SportsFitness',
  'TELECOMMUNICATIONS' = 'Telecommunications',
  'TEXTILES' = 'Textiles',
  'TRANSLATION_LOCALIZATION' = 'TranslationLocalization',
  'TRANSPORTATION_LOGISTICS' = 'TransportationLogistics',
  'VIRTUAL_REALITY_AUGMENTED_REALITY' = 'VirtualRealityAugmentedReality',
  'WASTE_MANAGEMENT' = 'WasteManagement',
  'WELLNESS_HEALTH_LIFESTYLE' = 'WellnessHealthLifestyle',
  'WHOLESALE_DISTRIBUTION' = 'WholesaleDistribution',
  'OTHER' = 'Other',
}
